[phases.setup]
nixPkgs = ["nodejs", "python39"]

[phases.install]
cmds = ["pip install -r requirements.txt", "cd frontend && npm install && cd .."]

[phases.build]
cmds = ["cd frontend && npm run build && cd .."]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"
